# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Justin Hong
# email: 
description: > # this means to ignore newlines until "baseurl:"
  Welcome! Iâ€™m Justin Hong, a Los Angeles-based software engineer. 
  This is my programming-related website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abigsmall.github.io" # the base hostname & protocol for your site
twitter_username: abigsmall
github_username:  abigsmall

# Build settings
markdown: kramdown
